### ISSUE TITLE
local-dev-ens Deploy Module Doesn't Output `/ens/testnet/...` URI

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1138]
When using the local-dev-ens deploy module, the URI that is output is a mainnet ENS URI, and does not have the `/testnet/` network in the path.

I also think it would make more sense to use `/local/` potentially? If we make the change to `/local/` we need to change all other occurrences of `/testnet/`.

**Comment by namesty** [comment]
The `local-dev-ens` deploy module was removed on #1097, because its purpose was having a single package to register an ENS name recursively AND deploy a wrapper to ENS at the same time; at the expense of being tightly coupled to our `eth-ens-ipfs` infra module. In its place, we have a separate deploy module to just register names recursively using any provider/network.

That said, I added the network name used to all ENS deploy modules's outputs in #1097 :D , as logically, the same principle of outputting the network would apply to the other ENS modules.
