### ISSUE TITLE
Bug: workflow validation succeeds when it should fail

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1227]
**Describe the bug**
Workflow validation is succeeding when it clearly should fail. I'm not sure under what conditions this occurs, but it seems validation always succeeds.

**Expected behavior**
I expected validation to fail.

**Screenshots / logs**
<img width="1440" alt="Screen Shot 2022-09-09 at 1 51 06 PM" src="https://user-images.githubusercontent.com/39842820/189311628-4e389a23-6dd9-4db7-9be7-e7b1acd569ac.png">

**Relevant environment details:**
- OS: MacOS

**Comment by fetsorn** [comment]
Please correct me if I'm wrong, but I think this is expected cue behaviour
You're testing an object `data: { "token": {}, "balance": {}, "values": []}` against a cue schema `data: { "result": "", "error": "", "id": ""}, error?: _|_ }`
Since the object doesn't have the fields that the schema is validating, validation succeeds.
To validate that the "data" object only has the fields specified in the schema, try to use a [closed struct](https://cuelang.org/docs/tutorials/tour/types/closed/)
Like this `data: { close({ "result": "", "error": "", "id": ""}), error?: _|_ }`

**Comment by krisbitney** [comment]
> Please correct me if I'm wrong, but I think this is expected cue behaviour You're testing an object `data: { "token": {}, "balance": {}, "values": []}` against a cue schema `data: { "result": "", "error": "", "id": ""}, error?: _|_ }` Since the object doesn't have the fields that the schema is validating, validation succeeds. To validate that the "data" object only has the fields specified in the schema, try to use a [closed struct](https://cuelang.org/docs/tutorials/tour/types/closed/) Like this `data: { close({ "result": "", "error": "", "id": ""}), error?: _|_ }`

Okay, I see. It looks like I'm just using cue wrong. Thanks!
