### ISSUE TITLE
Support GraphQL Subscriptions

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#198]
Support GraphQL subscription queries. The exact implementation & considerations are still to be determined.

Some initial thoughts:
- Subscriptions methods would be able to run in the background, dispatching results back to the caller.
- Specifying the subscription method's update frequency (allotted CPU time) would be nice.
- Research existing GraphQL subscription implementations.

Use Cases:
- Subscribe to a collection, receiving new items as they become available.
- Perform some arbitrary update logic that must run at some frequency.

**Comment by krisbitney** [comment]
**GraphQL subscriptions specification**
Since reference docs aren't yet available for subscriptions, the [graphql faq](https://graphql.org/faq/#where-is-the-documentation-for-subscriptions) points us to the specification: https://spec.graphql.org/draft/#sec-Subscription

**GraphQL subscriptions implementations**
- graphql.js source code for graphql client interface spec implementation: https://github.com/graphql/graphql-js/tree/main/src/subscription
- graphql-subscriptions package for server-side implementation (used in Apollo Server): https://github.com/apollographql/graphql-subscriptions
- graphql-ws package for alternative server-side implementation (used in express-graphql, graphql-yoga): https://github.com/enisdenjo/graphql-ws
- graphql-helix package for alternative server-side implementation supporting both server-push and client-pull subscription types, and only dependency is graphql.js: https://github.com/contrawork/graphql-helix/blob/a2203d336c812c7f19fe32b14a1cead10005829e/packages/core/lib/process-request.ts#L184

**Some developer experiences that might inspire the graphql schema interface implementation:**
- @withSubscription directive: https://dgraph.io/docs/graphql/subscriptions/
- subscription type (this is a more standard approach): https://www.apollographql.com/docs/react/data/subscriptions/

**Some developer experiences that might inspire the implementation of client return values:**
- ECMAScript proposal for 'Observable' standard: https://github.com/tc39/proposal-observable
- ReactiveX: http://reactivex.io/
- Rxjs: https://github.com/ReactiveX/rxjs
- Android LiveData: https://developer.android.com/topic/libraries/architecture/livedata#:~:text=LiveData%20Overview%20Part%20of%20Android%20Jetpack.%20LiveData%20is,app%20components%2C%20such%20as%20activities%2C%20fragments%2C%20or%20services.
- Kotlin Flows: https://kotlinlang.org/docs/flow.html

**Comment by krisbitney** [comment]
I'm thinking of two different ways of implementing subscriptions. I'm looking for feedback!

#### Subscription logic in WASM
Subscriptions imply the use of something like generator functions. A generator function can return values without completing execution; instead, a generator function “yields” a value, suspends, and then resumes. A subscription function might behave like:
```
myGenerator(): DataStructure {
    val cancelled = checkIfCancelled();
    while (!cancelled) {
        val data = checkForNewData();
        if (data) {
            yield data;
        }
        sleep(1000);
        cancelled = checkIfCancelled();
    }
}
```

The main benefit of this approach is state persistence between subscription calls.

AssemblyScript does not implement asynchronous behaviors, nor are they natively available in WASM (with some exceptions). However, it is possible to [asyncify](https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html) WASM using inline WASM and the binaryen compiler, which AssemblyScript uses. It is therefore possible to write an AssemblyScript package that implements behavior similar to that of generator functions, such as a yield(buffer) function that could be called. This would become a required dependency of AssemblyScript Polywrappers that implement subscriptions.

Note that Rust natively implements generator functions.

On the Client side, each subscription would generate a new thread to manage the subscription. The thread would call the async generator function and accept data transfers without closing the thread. The thread should only be canceled when the generator function completes execution or when the user requests it be canceled.

Since WASM calls in the JS Client are already being asyncified, a background thread is not really necessary. Rather, I believe it is possible to implement the "background process" as a function running in an async loop that awaits data or cancel signals from WASM modules.

#### Subscription logic in TypeScript
Alternatively, The subscription logic can be implemented fully in the Client. Subscription functions in Polywrappers would look just like Query and Mutation functions. As with Mutation, the graphql Subscription type would be a convention that indicates the developers wrote the functions with particular behavior in mind. The Client can make periodic calls to the subscription function, or be provided a callback that is periodically called to determine whether a new WASM invocation is necessary.

One benefit of this approach is that it need not be limited to graphql Subscription types. Rather, the same implementation can be used to periodically make Query and Mutation calls by adding a new function `client.Subscribe`, or by adding options to `client.Query(current stuff, options)`, or by interpreting a graphql directive `@subscribe(options)` to a query.

Another benefit is that this approach would be easier to implement--there would be no need to worry about asyncify, inline assembly, or new mustache templates.

A downside to this approach is that API developers have less control over subscription logic. Developers can of course write subscription functions that mimic the behavior of generators based on the assumption that the subscription function will be called repeatedly and each returned value is intermittent. However, developers lose state persistence between yields/calls (how important is this?).

Some other limitations are more easily surmountable. It would be nice to have a way to notify the client when a subscription is completed (perhaps a returned null value can indicate this?). Developers are also unable to choose factors like sleep duration, leaving those decisions instead to the user who may have less knowledge about desirable update frequencies for any given subscription (perhaps developers could use schema directives to define a default time between calls?).

#### These are not exclusive
It is possible to implement both WASM-generator subscriptions and subscription-like calls on Query functions based on a callback, a time period, or even block number iterations.

With both implementations, return values will be wrapped in a data structure that is something like an AsyncGenerator or AsyncIterator in order to comply with the official graphql spec (or perhaps the option of an observable data structure as used in reactive programming frameworks). Cached references to the return values can be stored in the API/plugin instances (via WasmWeb3Api.ts and PluginWeb3Api.ts), so that updates can be pushed to the data structure. The API instances themselves are already cached by the Client, and presumably will remain cached while subscriptions are active.

**Comment by dOrgJelli** [comment]
Talked w/ @krisbitney about this today, here were our conclusions:
1. While implementing the `type Subscription` in GraphQL is nice syntactically, it also implies we'd be supporting a new Wasm module `subscription.wasm`. This may be something we want to do in the future, so that we can support additional Wasm based helper methods (like yield), but isn't required for right now since we can implement a client-side only implementation which uses standard mutation & query methods (more on this below).
2. For the use-cases we talked about, we think we can accomplish all of them (initially) with a client-side only approach. Here's what that would look like:

**Base Interface**
```typescript
client.subscribe({
  query: "...",
  frequency: { ms: 200 }
})
```
where `subscribe` returns an async-iterator.

**Simple Example**
```typescript
client.subscribe({
  query: "mutation { someNormalMutation }",
  frequency: { ms: 200 }
})
```

**Use-Case Example**
```typescript
let latestBlock = 0;
const events = [];

client.subscribe({
  query: `query { getEthereumEvents(block: $block) }`,
  variables: { block: latestBlock },
  frequency: { sec: 17 }
}).pipe((result: { events, latestBlock }) => {
  latestBlock =  result.latestBlock;
  events.push(result.events);
})
```

**Object Oriented Use-Case**
```typescript
class Events {
  latestBlock: number = 0;
  events: Event[] = [];
  subscription: Subscription;

  constructor() {
    this.subscription = client.subscribe({
      query: `query { getEthereumEvents(block: $block) }`,
      variables: { block: this.latestBlock },
      frequency: { sec: 17 }
    }).pipe((result: { events, latestBlock }) => {
      this.latestBlock =  result.latestBlock;
      this.events.push(result.events);
    })
  }

  stop() {
   this.subscription.stop();
  }
}

const events = new Events();
events.events
events.latestBlock
events.stop()
```

**Comment by krisbitney** [comment]
Make sure to bring sunglasses cause this feature will be lit
