### ISSUE TITLE
Improved PR + Release Workflow (Increase Code Velocity)

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#325]
Implement a system of 3 branches, 2 of which will have continuous deployment. Ordering these branches from most stable to least:
1. **Release** (ex: `prealpha`)
2. **Release Candidate** (ex: `prealpha-rc`)
3. **Dev** (ex: `prealpha-dev`)

Branch policies will be configured in the following ways:
1. **Release** - 1 or more publishers (individuals listed in the [`.github/PUBLISHERS`](https://github.com/Web3-API/monorepo/blob/prealpha/.github/PUBLISHERS) file) must approve.
2. **Release Candidate** - code owners (individuals listed in the [`.github/CODEOWNERS`](https://github.com/Web3-API/monorepo/blob/prealpha/.github/CODEOWNERS) file) must approve. These individuals will be chosen based the files modified in the PR.
3. **Dev** - 2 or more developers working on the project must approve. This is intended to be the fastest path, to help improve code velocity.

Continuous deployments will be configured in the following ways:
1. **Release** - Versions will take the form of `#.#.#-name.#` where `-name` could be `prealpha`, `alpha`, `beta`, or completely omitted if release is production read (along with the final trailing `.#`.
2. **Release Candidate** - Versions will take the form of `#.#.#-name.#-rc.#` where `-rc.#` will continually increment until a release is made. Note that the version before `-rc.#` should be the next release. So if the current release is `0.0.1-prealpha.55`, then the Release Candidate version should be `0.0.1-prealpha.56-rc.#`.

**Comment by kev-ngo** [comment]
This process looks good.  Is there typically a best practice to measure code velocity?

Edit: I just saw Diego's spreadsheet.

**Comment by dOrgJelli** [comment]
Hmmm, interesting question @kev-ngo. I think the main metric this is aiming to help improve is:
* Time from PR creation to PR merge

This is something we could measure manually, not sure if there's a tool out there that can surface this for us though.

**Comment by jessebmiller** [comment]
Agile and Lean are two good places to look for velocity metrics.

Traditionally agile includes story writing and complexity point estimation. In scrum you'd measure "velocity" as the number of complexity points you shipped to production in a sprint. This turns out to take quite a lot of time and energy, and is difficult to make consistent (a team has to get good at estimation together and per project).

Lean prefers to look at lead times and cycle times. Cycle time is how long a "piece" (feature, widget, bugfix, etc.) takes to be released to production from the time engineers begin actively working on it. Lead time is the time it takes from the identification of a need (discovering the need for a feature, or discovering a bug, etc.) to it's solution being delivered to users (deployed to production).

I've tracked both and have found lead and cycle times to be more valuable and less costly to implement. I like to track a rolling percentile of lead times and cycle times for this.
