### ISSUE TITLE
React web3 api wrapper - Race condition issue on execute()

### ISSUE THREAD

**Issue by jeffscottward** [Web3-API/prototype#350]
When trying to execute a query within web3hub using the provider and the useWeb3ApiQuery hook, there is a race condition when trying to get a response back. Async/Await does not seem to fix the issue.

<img width="565" alt="Screen Shot 2021-05-26 at 2 53 55 PM" src="https://user-images.githubusercontent.com/1263486/119715804-665dd600-be32-11eb-989f-07174198ab89.png">
<img width="575" alt="Screen Shot 2021-05-26 at 2 54 04 PM" src="https://user-images.githubusercontent.com/1263486/119715805-66f66c80-be32-11eb-8aa4-c06db081943c.png">
<img width="1311" alt="Screen Shot 2021-05-26 at 2 54 51 PM" src="https://user-images.githubusercontent.com/1263486/119715806-66f66c80-be32-11eb-8c1e-4563de22e38b.png">

**Comment by jeffscottward** [comment]
https://github.com/Web3-API/web3hub/blob/jeff/playground-eject/packages/ui/src/components/Playground.tsx#L84-L107

**Comment by dOrgJelli** [comment]
Hey @jeffscottward, I think the problem is that the `errors` and `queryResponse` you're using are cached in the scope of the `runQuery` method, and are not representative of the latest render that occurs from the internal `setState`. Instead of using these values from the `useWeb3ApiQuery`, you could instead get them directly from the `execute()` function's returned result.

**Comment by jeffscottward** [comment]
Ahhh interesting ok - will try that cc @cbrzn

**Comment by dOrgJelli** [comment]
This has been fixed
