### ISSUE TITLE
Bug: Unable to import "imported" types from other wrappers

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#519]
For example, in wrapper `A` we may have:
```
#import { Query } into ImportantDep from "ens/important.eth"

type Query {
  someFunc: String!
}
```

and in wrapper `B` we may want to re-use `ImportantDep_Query` like so:
```
#import { Query, ImportantDep_Query } into A from "ens/a.eth"

type Query {
  anotherFund: String!
}
```

# Considerations
A way to work around this would be to re-import `ImportantDep_Query` into wrapper `B`. Is this more ideal? If so, why?

**Comment by nerfZael** [comment]
Why not use 
A:
```typescript
#import { Query } into ImportantDep from "ens/important.eth"

type Query {
  someFunc: String!
}

type ImportantDepQuery implements ImportantDepQuery { }
```
B:
```typescript
#import { ImportantDepQuery } into A from "ens/a.eth"

type Query {
  someFunc: String!
}

```

That way you explicitly re-export it (so you're not re-exporting as a side effect)

Note: I do believe there are use cases for re-export and using the suggested work around ("re-import ImportantDep_Query into wrapper B") is not appropriate in all use cases.

**Comment by brandonchuah** [comment]
I prefer to not re import in B but import it from A. In the case that A is an interface, you would know that you are using the types from the interface. Also it keeps the implementation - B in this case cleaner.

**Comment by dOrgJelli** [comment]
Great point @nerfZael, did not think of that.

I think for me, this is problematic because it requires the developer of `A` to know what users will need from its schema. The developer of `B` may want to re-use a dependency of `A` that has not be re-exported.

For example: I'm using the ethereum package, and want to re-use the same exact hashing library it's using under the hood.

**Comment by nerfZael** [comment]
> I think for me, this is problematic because it requires the developer of A to know what users will need from its schema

Yes, the developers of an API definitely need to know what users want from the API :D

An analogy in OOP world would be that you're trying to use a private field/method of a class that you imported from a library which is definitely not recommended from the developers of that lib (otherwise it'd be public, or in our case: re-exported).

I get what you're trying to do and it's a valid use case, but implicitly re-exporting imported deps and in that way not letting developers full control over what they expose to the user is not something that's good practice, imo.
We can either re-export the hashing functionality by using the "implements" keyword or we can try to solve this problem in some other clever way (that'd require us to make custom built-in functionality for that), but it's a general problem with libraries in any language
