### ISSUE TITLE
Support Better Error Handling in Wasm

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#643]
Currently when a wasm module performs a "subinvoke" and calls into another wasm module, there's no way of programatically handling the error that's returned. Instead an exception is thrown.

This is not suitable for situations where you want to call a function, see if it fails, and then call another function. For example: https://github.com/polywrap/monorepo/blob/8d659a9101e6097c659c56385871a980af9dcacc/packages/js/plugins/ipfs/src/resolvers.ts#L25-L50

**Comment by dOrgJelli** [comment]
Related conversation: https://discord.com/channels/796821176743362611/814588073581084723/940914201088643142

**Comment by dOrgJelli** [comment]
One way we can implement is to augment the `subinvoke` functionality within the Wasm runtime, as it already is aware of the error being returned.

We would simply modify the code to return the error instead of `throw`ing it. See here: https://github.com/polywrap/monorepo/blob/0512e06efafaa2564fab38f68549b2a18923bb8f/packages/wasm/as/assembly/subinvoke.ts#L42-L48

We want to make sure that this change does not change the developer experience for wrapper developers in a negative way. Here are two options for what the new developer experience looks like provided this example:
https://github.com/polywrap/monorepo/blob/0512e06efafaa2564fab38f68549b2a18923bb8f/packages/test-cases/cases/apis/simple-storage/mutation/index.ts#L5-L10

## Option 1: Return Result<TData, Error>
```typescript
const res = Ethereum_Mutation.callContractMethod({
    address: input.address,
    method: "function set(uint256 value)",
    args: [input.value.toString()],
    connection: input.connection
});

res.error
res.data
```
**Pros:** Very similar to other languages like Rust for example. Requires the user to handle errors.
**Cons:** Requires users to handle errors. Breaking change for wrappers written using the old syntax.

## Option 2: Optional No-Throw Method
```typescript
const res = Ethereum_Mutation.Try.callContractMethod({
    address: input.address,
    method: "function set(uint256 value)",
    args: [input.value.toString()],
    connection: input.connection
});

res.data;
res.error;
```
**Pros:** Additive non-breaking change. Users can decide what calls can throw and which can't.
**Cons:** Requires users to know about this new feature. Users by default won't handle errors, calls will throw.

## Option 3: Return Invokable<TData>
```typescript
const invokable = Ethereum_Mutation.callContractMethod({
    address: input.address,
    method: "function set(uint256 value)",
    args: [input.value.toString()],
    connection: input.connection
});

// throws
const data = invokable.invoke();

// catches
const res = invokable.try();

res.data;
res.error;
```
**Pros:** Users can decide what calls can throw and which can't. Very similar to other libraries like Web3.js & Ethers.js for example. Enables us to build upon this new `Invokable` construct.
**Cons:** Breaking change for wrappers written using the old syntax.

An example of how we can use this new `Invokable` construct in a cool way is sending multiple invocations at once.
```typescript
const invokes: Invokable[] = [];

for (let i = 0; i < 10; ++i) {
  invokes.push(
    Ethereum_Mutation.callContractMethod({
      address: input.address,
      method: "function set(uint256 value)",
      args: [input.value.toString()],
      connection: input.connection
    })
  )
}

const results = Invokable.all(invokes);

results[0].data;
results[0].error;
```

**Comment by dOrgJelli** [comment]
If we go with Option 2, we could extend it to support the `Invokable` construct in the future like so:
```typescript
const invokable = Ethereum_Mutation.Invokeable.callContractMethod({
    address: input.address,
    method: "function set(uint256 value)",
    args: [input.value.toString()],
    connection: input.connection
});

const data = invokable.invoke();
const res = invokable.try();
```

**Comment by dOrgJelli** [comment]
After some discussion with @Niraj-Kamdar @krisbitney @kev-ngo @rihp, we've decided Option 2 above is the best because it's a non-breaking & additive change, which can support future extension fairly easily.

**Comment by nerfZael** [comment]
- Why are we afraid of a breaking change in this instance? It's a simple thing for the wrap developers to change when they install a new version of the toolchain (they can throw an error if it exists and have the same functionality)
- Option 2 seems like a band-aid approach to me. We're mixing two types of properties (module methods and our custom Try property) in the module object, and we're relying on casing to separate them. I think this is a  bad pattern to have when it is not absolutely necessary.
- Handling an error instead of just throwing should be the standard approach, and "breaking" current wrapper implementations by releasing that change would be a good way to communicate that to the developer.

Honestly, with this decision, it feels like we're walking on eggshells for a feature that even a vast developer base wouldn't mind terribly to have it break for them. Toolchains/Libs release breaking changes all the time. It's not something that should be so much that it gets in the way of good architecture, especially when the change is so small.

If we're so worried about breaking changes, why don't we, yet, follow SemVer standards?

I really wish I was included in this discussion
