### ISSUE TITLE
CLI: Integrate Wrappers CLI Deployment (IPFS & ENS)

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#670]
@nerfZael has done a lot of great work creating the `wrappers` CLI which provides:
- IPFS publishing via wrappers.io gateway
- ENS publishing (mainnet & rinkeby)

We should integrate this functionality into the main `w3` CLI.

https://github.com/nerfZael/wrappers

**Comment by nerfZael** [comment]
I think we should start thinking about moving blockchain specific commands and functionality to chain specific CLI tools.
Otherwise, we will start bloating our w3 CLI with chain specific logic for many chains. (Ethereum/ENS publishing, Near publishing, Polkadot publishing)
We are trying to be chain agnostic, so this kind of move makes sense.

My suggestion would be to, still, add IPFS publishing to w3 CLI, but move ENS to an Ethereum CLI

**Comment by dOrgJelli** [comment]
Instead of having separate CLIs, I was thinking these different types of chain-specific publishing steps could be extensions to the CLI.

We're already doing this with the "test-env" in the "Modular Test Environments" PR, allowing developers to add their own services to run their wrappers against.

**Comment by dOrgJelli** [comment]
But in general I agree, CLI cannot be bloated with chain-specific operations, and it must be done in an extendable way.

**Comment by nerfZael** [comment]
Yes, we could go the way of extensions. I'll check out how it's done with test-env as I am not familiar with it

**Comment by Niraj-Kamdar** [comment]
I agree on going with the extensions route.

**Comment by nerfZael** [comment]
A feature that we should support with this and that is not already supported with wrappers CLI, is the ability to publish an IPFS hash to ENS, instead of needing to publish build folder to IPFS and then IPFS to ENS
