### ISSUE TITLE
Remove modules infrastructure from the CLI, Client and Core

### ISSUE THREAD

**Issue by namesty** [Web3-API/prototype#887]
So far, we've worked from GraphQL's concept of Query and Mutation modules. Supporting `n` named-modules would be similar to having a monorepo structure for wrappers by default. Therefore, we're removing the concept of modules and associated infrastructure from the toolchain.

This issue entails removing the infrastructure mentioned above, from the parts of the toolchain outside of the schema pipeline. Some identified subtasks (more may appear along the way) are:

- Remove the modules key
- Changes to compiler
- Changes to query and build commands, maybe codegen?
- Remove module argument from invoke and query
- Updating tests and testing related utilities that use the client (like buildAndDeploy, or the e2e tests across the monorepo)

**Comment by cbrzn** [comment]
Would it makes sense to say that the new manifest; which will be something like:
```yaml
format: 0.0.1-prealpha.9
name: NumberTypes
build: ./web3api.build.yaml
language: wasm/assemblyscript
schema: ./schema.graphql
main: ./src/index.ts
```
is non-compatible with the previous versions? The reason for this is that currently we have two entry points (query & module) and now we have one. So I see two paths here: 
1. Take one of both, which I don't think makes sense because we would be ignoring one module (or query or mutation) and I don't think this is the right approach
2. Just make this an explicit breaking change. I think this is the way to go, we are at the perfect moment to introduce this kind of change. Making it an explicit breaking change would mean that, if you try to build your wrapper with an older version than this, the CLI will explicitly tell you that you need to update.

I will start implementing the changes with these assumptions but would love to hear your thoughts :) @Niraj-Kamdar @namesty @dOrgJelli 

edit: IIRC, the same happened with plugins, in which version `0.0.1-prealpha.2` was non-compatible with version `0.0.1-prealpha.1`

**Comment by Niraj-Kamdar** [comment]
@cbrzn I think this makes sense!

**Comment by dOrgJelli** [comment]
Makes sense @cbrzn, but can we keep the `module:` property name, and not rename that to `main:`?

**Comment by Niraj-Kamdar** [comment]
> Makes sense @cbrzn, but can we keep the `module:` property name, and not rename that to `main:`?

Any particular reason for that, since from what I have seen in other languages, most of the languages call the entry-point file main (Ex: node, rust, etc)?

**Comment by dOrgJelli** [comment]
It's just because that's what we call it in the rest of our codebase, "module". Here are the names we use:
```
Wrapper ->
  Module ->
    Methods
```
